
import sys
import os

naf_utilities_path = os.environ["TEA_PATH"] + "/code/notes/utilities"
sys.path.insert(0, naf_utilities_path)

import naf_utilities
import news_reader

def get_lemmas(ixa_tok_output):

    """ gets lemma taggings within a naf doc generated by ixa pipe module.
    """

    lemmas = []

    for naf_term in naf_utilities._get_naf_terms(ixa_tok_output):

        lemma      = naf_term.attrib["lemma"]

        # I think I can just change t1 to w1, seems like one to one mapping.
        id_str       = naf_term.attrib["id"].replace('t','w')

        lemmas.append({"lemma":lemma, "id":id_str})

    return lemmas


if __name__ == "__main__":
    pass
# EOF

